# Generated by Django 2.2.10 on 2020-06-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://s3.amazonaws.com/ODNUploads/56394e2bb0221placeholder_food_item_2.png', max_length=500),
        ),
    ]
